SELECT * FROM PMA_COMMENT;

SELECT * FROM PMA_SHOP;

SELECT * FROM PMA_USER;
insert into pma_user values(seq_pma_user.nextval,'admin',1,'admin','admin','',0)

-- PMA_USER AUTH 
-- 1:관리자 / 3:사용자

alter table PMA_COMMENT add content varchar2(500) not null

SELECT SEQ ,NAME, ADDR,TEL,CATEGORY,MENU,XPOS,YPOS,IMGFILE,DEL
		FROM PMA_SHOP
		ORDER BY SEQ ASC
		
INSERT INTO PMA_SHOP(SEQ ,NAME, ADDR,TEL,CATEGORY,MENU,XPOS,YPOS,IMGFILE,DEL) 
		VALUES(SEQ_PMA_SHOP.NEXTVAL,'국회의사당 버거킹2','서울시 영등포구2','02-1234-5678','패스트푸드','와퍼',0,0,'',0)
		
commit

SELECT * FROM PMA_SHOP;		
		
SELECT SEQ ,NAME, ADDR,TEL,CATEGORY,MENU,XPOS,YPOS,IMGFILE,DEL
		FROM PMA_SHOP
		WHERE ADDR LIKE '%서울%'
		
SELECT SEQ ,NAME, ADDR,TEL,CATEGORY,MENU,XPOS,YPOS,IMGFILE,DEL
		FROM PMA_SHOP
		ORDER BY SEQ ASC
		
		
commit
		